### ISSUE TITLE
a question about the goal generator in human evaluation for the end-to-end dialog task

### ISSUE THREAD

**Issue by boliangz** [ConvLab/ConvLab-2#11]
Is the goal generator used in human evaluation the same one as the one used to generate Multiwoz dataset?

For example, we noticed that the leave time mentioned in the train domain is always "leaving after some time". Will this be the case in the human evaluation as well, which means there will be no goal that lets the user to say "I want to leave before XXX (times)"?  Thanks!

**Comment by jincli** [comment]
@boliangz   The goal generator used in human evaluation will be the same one as in the automatic evaluation.

**Comment by boliangz** [comment]
Thanks.
