### ISSUE TITLE
fail_book in End-to-end Multi-domain Task Completion Dialog

### ISSUE THREAD

**Issue by boliangz** [ConvLab/ConvLab-2#3]
Quite a few dialogs in Multiwoz 2.0 contain fail_book status in goal, where there is no booking available for user's request, for example, user: "Please book a table for 7 people at 11:45 on Monday .", system: "I'm sorry that time slot is not available that day . Would you care to try for a different time or day perhaps ?". 

It seems whether the booking is successful depends on the user's goal (there is a fail_book status in the user's goal). This means that in order to make a correct prediction, the system needs to know whether the book fails or not. My question is: does the evaluation test set contain fail_book status, if so, how we can get this information if without users' goal? 

A few more questions about the evaluation test set:
1. would you provide some sample test sets?
2. the instruction says "The system will be evaluated in MultiWOZ 2.1 dataset setting with ConvLab-2.", does this mean the test set is the "test.json" of MultiWOZ 2.1 dataset?

**Comment by jincli** [comment]
@boliangz  'fail_book' will be disabled in the evaluation. The automatic evaluation is simulator-based, so no test sets will be used. When we mentioned it is based on MultiWOZ 2.1 dataset, it means the simulator and evaluator are constructed based on MultiWOZ 2.1 dataset, including data format, domain/slot distribution for goal sampling, etc. You can refer to https://github.com/thu-coai/ConvLab-2/blob/master/tests/test_BERTNLU-RuleDST-RulePolicy-TemplateNLG.py for the automatic evaluation approach. For human evaluation, it will be similar to https://github.com/thu-coai/ConvLab-2/tree/master/convlab2/human_eval

**Comment by boliangz** [comment]
Thanks for the quick response.
