### ISSUE TITLE
changes of automatic evaluation for end-to-end multi-domain task completion dialog

### ISSUE THREAD

**Issue by boliangz** [ConvLab/ConvLab-2#8]
We did not notice a major change in the automatic evaluation script until we pulled the latest Convlab2 recently. We noticed a drastic decrease in our automatic evaluation scores. From the "Updates" section, we did not see any changes related to this. Is there any other source that you post updates to? 

Considering this situation and the pandemics, we might need more time on making changes to our systems. We'd like to ask for a few day's extension (for all teams) if all possible. Thanks.

**Comment by jincli** [comment]
@boliangz  Most changes in convlab-2 automatic evaluator for bug fix and robustness (grounding) of the evaluator.  Which major change did you mean?

**Comment by boliangz** [comment]
Commits:

**Comment by jincli** [comment]
@boliangz  The final_goal_analyze is to add db requested results to the goal for db lookup (db grounding). However, we've used relatively low fuzzymatch rate to relax the constraints. Looking into whether requested results are valid should help debug your system quickly.

**Comment by boliangz** [comment]
Thanks for the suggestions. Really appreciate it if changes like this can be marked in the future.
